#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="lottery")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertbetForm(betForm instance);
  partial void UpdatebetForm(betForm instance);
  partial void DeletebetForm(betForm instance);
  partial void Insertcompany(company instance);
  partial void Updatecompany(company instance);
  partial void Deletecompany(company instance);
  partial void Insertmember(member instance);
  partial void Updatemember(member instance);
  partial void Deletemember(member instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["lotteryConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<betForm> betForms
	{
		get
		{
			return this.GetTable<betForm>();
		}
	}
	
	public System.Data.Linq.Table<bulletin> bulletins
	{
		get
		{
			return this.GetTable<bulletin>();
		}
	}
	
	public System.Data.Linq.Table<company> companies
	{
		get
		{
			return this.GetTable<company>();
		}
	}
	
	public System.Data.Linq.Table<member> members
	{
		get
		{
			return this.GetTable<member>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.betForm")]
public partial class betForm : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _periodId;
	
	private string _externalId;
	
	private int _companyId;
	
	private int _parentId;
	
	private string _betType;
	
	private string _betBranch;
	
	private string _chooseBall;
	
	private int _combo;
	
	private decimal _betAmount;
	
	private decimal _rate;
	
	private decimal _totalBet;
	
	private decimal _winAmount;
	
	private string _status;
	
	private System.DateTime _createDateTime;
	
	private string _createIP;
	
	private System.Nullable<System.DateTime> _checkoutDateTime;
	
	private decimal _deliverAmount;
	
	private bool _isDeliver;
	
	private string _lotteryResult;
	
	private decimal _r8;
	
	private decimal _r7;
	
	private decimal _r1;
	
	private string _betRemark;
	
	private string _username;
	
	private System.Nullable<int> _l9;
	
	private System.Nullable<int> _l8;
	
	private System.Nullable<int> _l7;
	
	private System.Nullable<int> _l1;
	
	private System.DateTime _beginDateTime;
	
	private System.Nullable<System.DateTime> _deliveryDateTime;
	
	private System.DateTime _lastModifyDateTime;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnperiodIdChanging(string value);
    partial void OnperiodIdChanged();
    partial void OnexternalIdChanging(string value);
    partial void OnexternalIdChanged();
    partial void OncompanyIdChanging(int value);
    partial void OncompanyIdChanged();
    partial void OnparentIdChanging(int value);
    partial void OnparentIdChanged();
    partial void OnbetTypeChanging(string value);
    partial void OnbetTypeChanged();
    partial void OnbetBranchChanging(string value);
    partial void OnbetBranchChanged();
    partial void OnchooseBallChanging(string value);
    partial void OnchooseBallChanged();
    partial void OncomboChanging(int value);
    partial void OncomboChanged();
    partial void OnbetAmountChanging(decimal value);
    partial void OnbetAmountChanged();
    partial void OnrateChanging(decimal value);
    partial void OnrateChanged();
    partial void OntotalBetChanging(decimal value);
    partial void OntotalBetChanged();
    partial void OnwinAmountChanging(decimal value);
    partial void OnwinAmountChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OncreateDateTimeChanging(System.DateTime value);
    partial void OncreateDateTimeChanged();
    partial void OncreateIPChanging(string value);
    partial void OncreateIPChanged();
    partial void OncheckoutDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncheckoutDateTimeChanged();
    partial void OndeliverAmountChanging(decimal value);
    partial void OndeliverAmountChanged();
    partial void OnisDeliverChanging(bool value);
    partial void OnisDeliverChanged();
    partial void OnlotteryResultChanging(string value);
    partial void OnlotteryResultChanged();
    partial void Onr8Changing(decimal value);
    partial void Onr8Changed();
    partial void Onr7Changing(decimal value);
    partial void Onr7Changed();
    partial void Onr1Changing(decimal value);
    partial void Onr1Changed();
    partial void OnbetRemarkChanging(string value);
    partial void OnbetRemarkChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onl9Changing(System.Nullable<int> value);
    partial void Onl9Changed();
    partial void Onl8Changing(System.Nullable<int> value);
    partial void Onl8Changed();
    partial void Onl7Changing(System.Nullable<int> value);
    partial void Onl7Changed();
    partial void Onl1Changing(System.Nullable<int> value);
    partial void Onl1Changed();
    partial void OnbeginDateTimeChanging(System.DateTime value);
    partial void OnbeginDateTimeChanged();
    partial void OndeliveryDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OndeliveryDateTimeChanged();
    partial void OnlastModifyDateTimeChanging(System.DateTime value);
    partial void OnlastModifyDateTimeChanged();
    #endregion
	
	public betForm()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodId", DbType="VarChar(50)")]
	public string periodId
	{
		get
		{
			return this._periodId;
		}
		set
		{
			if ((this._periodId != value))
			{
				this.OnperiodIdChanging(value);
				this.SendPropertyChanging();
				this._periodId = value;
				this.SendPropertyChanged("periodId");
				this.OnperiodIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externalId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string externalId
	{
		get
		{
			return this._externalId;
		}
		set
		{
			if ((this._externalId != value))
			{
				this.OnexternalIdChanging(value);
				this.SendPropertyChanging();
				this._externalId = value;
				this.SendPropertyChanged("externalId");
				this.OnexternalIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyId", DbType="Int NOT NULL")]
	public int companyId
	{
		get
		{
			return this._companyId;
		}
		set
		{
			if ((this._companyId != value))
			{
				this.OncompanyIdChanging(value);
				this.SendPropertyChanging();
				this._companyId = value;
				this.SendPropertyChanged("companyId");
				this.OncompanyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentId", DbType="Int NOT NULL")]
	public int parentId
	{
		get
		{
			return this._parentId;
		}
		set
		{
			if ((this._parentId != value))
			{
				this.OnparentIdChanging(value);
				this.SendPropertyChanging();
				this._parentId = value;
				this.SendPropertyChanged("parentId");
				this.OnparentIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betType", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string betType
	{
		get
		{
			return this._betType;
		}
		set
		{
			if ((this._betType != value))
			{
				this.OnbetTypeChanging(value);
				this.SendPropertyChanging();
				this._betType = value;
				this.SendPropertyChanged("betType");
				this.OnbetTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betBranch", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string betBranch
	{
		get
		{
			return this._betBranch;
		}
		set
		{
			if ((this._betBranch != value))
			{
				this.OnbetBranchChanging(value);
				this.SendPropertyChanging();
				this._betBranch = value;
				this.SendPropertyChanged("betBranch");
				this.OnbetBranchChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chooseBall", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string chooseBall
	{
		get
		{
			return this._chooseBall;
		}
		set
		{
			if ((this._chooseBall != value))
			{
				this.OnchooseBallChanging(value);
				this.SendPropertyChanging();
				this._chooseBall = value;
				this.SendPropertyChanged("chooseBall");
				this.OnchooseBallChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_combo", DbType="Int NOT NULL")]
	public int combo
	{
		get
		{
			return this._combo;
		}
		set
		{
			if ((this._combo != value))
			{
				this.OncomboChanging(value);
				this.SendPropertyChanging();
				this._combo = value;
				this.SendPropertyChanged("combo");
				this.OncomboChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betAmount", DbType="Decimal(18,4) NOT NULL")]
	public decimal betAmount
	{
		get
		{
			return this._betAmount;
		}
		set
		{
			if ((this._betAmount != value))
			{
				this.OnbetAmountChanging(value);
				this.SendPropertyChanging();
				this._betAmount = value;
				this.SendPropertyChanged("betAmount");
				this.OnbetAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="Decimal(18,4) NOT NULL")]
	public decimal rate
	{
		get
		{
			return this._rate;
		}
		set
		{
			if ((this._rate != value))
			{
				this.OnrateChanging(value);
				this.SendPropertyChanging();
				this._rate = value;
				this.SendPropertyChanged("rate");
				this.OnrateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalBet", DbType="Decimal(18,4) NOT NULL")]
	public decimal totalBet
	{
		get
		{
			return this._totalBet;
		}
		set
		{
			if ((this._totalBet != value))
			{
				this.OntotalBetChanging(value);
				this.SendPropertyChanging();
				this._totalBet = value;
				this.SendPropertyChanged("totalBet");
				this.OntotalBetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_winAmount", DbType="Decimal(18,4) NOT NULL")]
	public decimal winAmount
	{
		get
		{
			return this._winAmount;
		}
		set
		{
			if ((this._winAmount != value))
			{
				this.OnwinAmountChanging(value);
				this.SendPropertyChanging();
				this._winAmount = value;
				this.SendPropertyChanged("winAmount");
				this.OnwinAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
	public System.DateTime createDateTime
	{
		get
		{
			return this._createDateTime;
		}
		set
		{
			if ((this._createDateTime != value))
			{
				this.OncreateDateTimeChanging(value);
				this.SendPropertyChanging();
				this._createDateTime = value;
				this.SendPropertyChanged("createDateTime");
				this.OncreateDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string createIP
	{
		get
		{
			return this._createIP;
		}
		set
		{
			if ((this._createIP != value))
			{
				this.OncreateIPChanging(value);
				this.SendPropertyChanging();
				this._createIP = value;
				this.SendPropertyChanged("createIP");
				this.OncreateIPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkoutDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> checkoutDateTime
	{
		get
		{
			return this._checkoutDateTime;
		}
		set
		{
			if ((this._checkoutDateTime != value))
			{
				this.OncheckoutDateTimeChanging(value);
				this.SendPropertyChanging();
				this._checkoutDateTime = value;
				this.SendPropertyChanged("checkoutDateTime");
				this.OncheckoutDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deliverAmount", DbType="Decimal(18,4) NOT NULL")]
	public decimal deliverAmount
	{
		get
		{
			return this._deliverAmount;
		}
		set
		{
			if ((this._deliverAmount != value))
			{
				this.OndeliverAmountChanging(value);
				this.SendPropertyChanging();
				this._deliverAmount = value;
				this.SendPropertyChanged("deliverAmount");
				this.OndeliverAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeliver", DbType="Bit NOT NULL")]
	public bool isDeliver
	{
		get
		{
			return this._isDeliver;
		}
		set
		{
			if ((this._isDeliver != value))
			{
				this.OnisDeliverChanging(value);
				this.SendPropertyChanging();
				this._isDeliver = value;
				this.SendPropertyChanged("isDeliver");
				this.OnisDeliverChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lotteryResult", DbType="VarChar(50)")]
	public string lotteryResult
	{
		get
		{
			return this._lotteryResult;
		}
		set
		{
			if ((this._lotteryResult != value))
			{
				this.OnlotteryResultChanging(value);
				this.SendPropertyChanging();
				this._lotteryResult = value;
				this.SendPropertyChanged("lotteryResult");
				this.OnlotteryResultChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r8", DbType="Decimal(18,4) NOT NULL")]
	public decimal r8
	{
		get
		{
			return this._r8;
		}
		set
		{
			if ((this._r8 != value))
			{
				this.Onr8Changing(value);
				this.SendPropertyChanging();
				this._r8 = value;
				this.SendPropertyChanged("r8");
				this.Onr8Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r7", DbType="Decimal(18,4) NOT NULL")]
	public decimal r7
	{
		get
		{
			return this._r7;
		}
		set
		{
			if ((this._r7 != value))
			{
				this.Onr7Changing(value);
				this.SendPropertyChanging();
				this._r7 = value;
				this.SendPropertyChanged("r7");
				this.Onr7Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r1", DbType="Decimal(18,4) NOT NULL")]
	public decimal r1
	{
		get
		{
			return this._r1;
		}
		set
		{
			if ((this._r1 != value))
			{
				this.Onr1Changing(value);
				this.SendPropertyChanging();
				this._r1 = value;
				this.SendPropertyChanged("r1");
				this.Onr1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betRemark", DbType="VarChar(50)")]
	public string betRemark
	{
		get
		{
			return this._betRemark;
		}
		set
		{
			if ((this._betRemark != value))
			{
				this.OnbetRemarkChanging(value);
				this.SendPropertyChanging();
				this._betRemark = value;
				this.SendPropertyChanged("betRemark");
				this.OnbetRemarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l9", DbType="Int")]
	public System.Nullable<int> l9
	{
		get
		{
			return this._l9;
		}
		set
		{
			if ((this._l9 != value))
			{
				this.Onl9Changing(value);
				this.SendPropertyChanging();
				this._l9 = value;
				this.SendPropertyChanged("l9");
				this.Onl9Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l8", DbType="Int")]
	public System.Nullable<int> l8
	{
		get
		{
			return this._l8;
		}
		set
		{
			if ((this._l8 != value))
			{
				this.Onl8Changing(value);
				this.SendPropertyChanging();
				this._l8 = value;
				this.SendPropertyChanged("l8");
				this.Onl8Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l7", DbType="Int")]
	public System.Nullable<int> l7
	{
		get
		{
			return this._l7;
		}
		set
		{
			if ((this._l7 != value))
			{
				this.Onl7Changing(value);
				this.SendPropertyChanging();
				this._l7 = value;
				this.SendPropertyChanged("l7");
				this.Onl7Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l1", DbType="Int")]
	public System.Nullable<int> l1
	{
		get
		{
			return this._l1;
		}
		set
		{
			if ((this._l1 != value))
			{
				this.Onl1Changing(value);
				this.SendPropertyChanging();
				this._l1 = value;
				this.SendPropertyChanged("l1");
				this.Onl1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beginDateTime", DbType="DateTime NOT NULL")]
	public System.DateTime beginDateTime
	{
		get
		{
			return this._beginDateTime;
		}
		set
		{
			if ((this._beginDateTime != value))
			{
				this.OnbeginDateTimeChanging(value);
				this.SendPropertyChanging();
				this._beginDateTime = value;
				this.SendPropertyChanged("beginDateTime");
				this.OnbeginDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deliveryDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> deliveryDateTime
	{
		get
		{
			return this._deliveryDateTime;
		}
		set
		{
			if ((this._deliveryDateTime != value))
			{
				this.OndeliveryDateTimeChanging(value);
				this.SendPropertyChanging();
				this._deliveryDateTime = value;
				this.SendPropertyChanged("deliveryDateTime");
				this.OndeliveryDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastModifyDateTime", DbType="DateTime NOT NULL")]
	public System.DateTime lastModifyDateTime
	{
		get
		{
			return this._lastModifyDateTime;
		}
		set
		{
			if ((this._lastModifyDateTime != value))
			{
				this.OnlastModifyDateTimeChanging(value);
				this.SendPropertyChanging();
				this._lastModifyDateTime = value;
				this.SendPropertyChanged("lastModifyDateTime");
				this.OnlastModifyDateTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bulletin")]
public partial class bulletin
{
	
	private int _id;
	
	private string _title;
	
	private string _contentText;
	
	private System.DateTime _createDateTime;
	
	private System.Nullable<System.DateTime> _updateDateTime;
	
	private int _createUserId;
	
	private System.Nullable<int> _updateUserId;
	
	private string _isEnabled;
	
	private System.Nullable<System.DateTime> _stickyDateTime;
	
	private System.Nullable<int> _companyId;
	
	public bulletin()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this._title = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contentText", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string contentText
	{
		get
		{
			return this._contentText;
		}
		set
		{
			if ((this._contentText != value))
			{
				this._contentText = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime NOT NULL")]
	public System.DateTime createDateTime
	{
		get
		{
			return this._createDateTime;
		}
		set
		{
			if ((this._createDateTime != value))
			{
				this._createDateTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> updateDateTime
	{
		get
		{
			return this._updateDateTime;
		}
		set
		{
			if ((this._updateDateTime != value))
			{
				this._updateDateTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createUserId", DbType="Int NOT NULL")]
	public int createUserId
	{
		get
		{
			return this._createUserId;
		}
		set
		{
			if ((this._createUserId != value))
			{
				this._createUserId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateUserId", DbType="Int")]
	public System.Nullable<int> updateUserId
	{
		get
		{
			return this._updateUserId;
		}
		set
		{
			if ((this._updateUserId != value))
			{
				this._updateUserId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEnabled", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
	public string isEnabled
	{
		get
		{
			return this._isEnabled;
		}
		set
		{
			if ((this._isEnabled != value))
			{
				this._isEnabled = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stickyDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> stickyDateTime
	{
		get
		{
			return this._stickyDateTime;
		}
		set
		{
			if ((this._stickyDateTime != value))
			{
				this._stickyDateTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyId", DbType="Int")]
	public System.Nullable<int> companyId
	{
		get
		{
			return this._companyId;
		}
		set
		{
			if ((this._companyId != value))
			{
				this._companyId = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.company")]
public partial class company : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _title;
	
	private System.Nullable<int> _principalId;
	
	private System.Nullable<System.DateTime> _createDateTime;
	
	private System.Nullable<System.DateTime> _updateDateTime;
	
	private System.Nullable<int> _updateUserId;
	
	private string _betRate;
	
	private string _defaultBetSetting;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnprincipalIdChanging(System.Nullable<int> value);
    partial void OnprincipalIdChanged();
    partial void OncreateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateTimeChanged();
    partial void OnupdateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnupdateDateTimeChanged();
    partial void OnupdateUserIdChanging(System.Nullable<int> value);
    partial void OnupdateUserIdChanged();
    partial void OnbetRateChanging(string value);
    partial void OnbetRateChanged();
    partial void OndefaultBetSettingChanging(string value);
    partial void OndefaultBetSettingChanged();
    #endregion
	
	public company()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principalId", DbType="Int")]
	public System.Nullable<int> principalId
	{
		get
		{
			return this._principalId;
		}
		set
		{
			if ((this._principalId != value))
			{
				this.OnprincipalIdChanging(value);
				this.SendPropertyChanging();
				this._principalId = value;
				this.SendPropertyChanged("principalId");
				this.OnprincipalIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> createDateTime
	{
		get
		{
			return this._createDateTime;
		}
		set
		{
			if ((this._createDateTime != value))
			{
				this.OncreateDateTimeChanging(value);
				this.SendPropertyChanging();
				this._createDateTime = value;
				this.SendPropertyChanged("createDateTime");
				this.OncreateDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> updateDateTime
	{
		get
		{
			return this._updateDateTime;
		}
		set
		{
			if ((this._updateDateTime != value))
			{
				this.OnupdateDateTimeChanging(value);
				this.SendPropertyChanging();
				this._updateDateTime = value;
				this.SendPropertyChanged("updateDateTime");
				this.OnupdateDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateUserId", DbType="Int")]
	public System.Nullable<int> updateUserId
	{
		get
		{
			return this._updateUserId;
		}
		set
		{
			if ((this._updateUserId != value))
			{
				this.OnupdateUserIdChanging(value);
				this.SendPropertyChanging();
				this._updateUserId = value;
				this.SendPropertyChanged("updateUserId");
				this.OnupdateUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betRate", DbType="NVarChar(MAX)")]
	public string betRate
	{
		get
		{
			return this._betRate;
		}
		set
		{
			if ((this._betRate != value))
			{
				this.OnbetRateChanging(value);
				this.SendPropertyChanging();
				this._betRate = value;
				this.SendPropertyChanged("betRate");
				this.OnbetRateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defaultBetSetting", DbType="NVarChar(MAX)")]
	public string defaultBetSetting
	{
		get
		{
			return this._defaultBetSetting;
		}
		set
		{
			if ((this._defaultBetSetting != value))
			{
				this.OndefaultBetSettingChanging(value);
				this.SendPropertyChanging();
				this._defaultBetSetting = value;
				this.SendPropertyChanged("defaultBetSetting");
				this.OndefaultBetSettingChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.member")]
public partial class member : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _username;
	
	private string _password;
	
	private int _levelId;
	
	private int _companyId;
	
	private string _externalId;
	
	private System.Nullable<int> _l9;
	
	private System.Nullable<int> _l8;
	
	private System.Nullable<int> _l7;
	
	private System.Nullable<int> _l1;
	
	private System.Nullable<System.DateTime> _loginDateTime;
	
	private string _loginIP;
	
	private int _parentId;
	
	private System.Nullable<System.DateTime> _createDateTime;
	
	private System.Nullable<System.DateTime> _updateDateTime;
	
	private System.Nullable<int> _updateUserId;
	
	private decimal _walletAmount;
	
	private System.Nullable<decimal> _rate;
	
	private string _betSetting;
	
	private string _loginGuid;
	
	private string _status;
	
	private string _nickname;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnlevelIdChanging(int value);
    partial void OnlevelIdChanged();
    partial void OncompanyIdChanging(int value);
    partial void OncompanyIdChanged();
    partial void OnexternalIdChanging(string value);
    partial void OnexternalIdChanged();
    partial void Onl9Changing(System.Nullable<int> value);
    partial void Onl9Changed();
    partial void Onl8Changing(System.Nullable<int> value);
    partial void Onl8Changed();
    partial void Onl7Changing(System.Nullable<int> value);
    partial void Onl7Changed();
    partial void Onl1Changing(System.Nullable<int> value);
    partial void Onl1Changed();
    partial void OnloginDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnloginDateTimeChanged();
    partial void OnloginIPChanging(string value);
    partial void OnloginIPChanged();
    partial void OnparentIdChanging(int value);
    partial void OnparentIdChanged();
    partial void OncreateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreateDateTimeChanged();
    partial void OnupdateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnupdateDateTimeChanged();
    partial void OnupdateUserIdChanging(System.Nullable<int> value);
    partial void OnupdateUserIdChanged();
    partial void OnwalletAmountChanging(decimal value);
    partial void OnwalletAmountChanged();
    partial void OnrateChanging(System.Nullable<decimal> value);
    partial void OnrateChanged();
    partial void OnbetSettingChanging(string value);
    partial void OnbetSettingChanged();
    partial void OnloginGuidChanging(string value);
    partial void OnloginGuidChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnnicknameChanging(string value);
    partial void OnnicknameChanged();
    #endregion
	
	public member()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_levelId", DbType="Int NOT NULL")]
	public int levelId
	{
		get
		{
			return this._levelId;
		}
		set
		{
			if ((this._levelId != value))
			{
				this.OnlevelIdChanging(value);
				this.SendPropertyChanging();
				this._levelId = value;
				this.SendPropertyChanged("levelId");
				this.OnlevelIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyId", DbType="Int NOT NULL")]
	public int companyId
	{
		get
		{
			return this._companyId;
		}
		set
		{
			if ((this._companyId != value))
			{
				this.OncompanyIdChanging(value);
				this.SendPropertyChanging();
				this._companyId = value;
				this.SendPropertyChanged("companyId");
				this.OncompanyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_externalId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string externalId
	{
		get
		{
			return this._externalId;
		}
		set
		{
			if ((this._externalId != value))
			{
				this.OnexternalIdChanging(value);
				this.SendPropertyChanging();
				this._externalId = value;
				this.SendPropertyChanged("externalId");
				this.OnexternalIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l9", DbType="Int")]
	public System.Nullable<int> l9
	{
		get
		{
			return this._l9;
		}
		set
		{
			if ((this._l9 != value))
			{
				this.Onl9Changing(value);
				this.SendPropertyChanging();
				this._l9 = value;
				this.SendPropertyChanged("l9");
				this.Onl9Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l8", DbType="Int")]
	public System.Nullable<int> l8
	{
		get
		{
			return this._l8;
		}
		set
		{
			if ((this._l8 != value))
			{
				this.Onl8Changing(value);
				this.SendPropertyChanging();
				this._l8 = value;
				this.SendPropertyChanged("l8");
				this.Onl8Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l7", DbType="Int")]
	public System.Nullable<int> l7
	{
		get
		{
			return this._l7;
		}
		set
		{
			if ((this._l7 != value))
			{
				this.Onl7Changing(value);
				this.SendPropertyChanging();
				this._l7 = value;
				this.SendPropertyChanged("l7");
				this.Onl7Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l1", DbType="Int")]
	public System.Nullable<int> l1
	{
		get
		{
			return this._l1;
		}
		set
		{
			if ((this._l1 != value))
			{
				this.Onl1Changing(value);
				this.SendPropertyChanging();
				this._l1 = value;
				this.SendPropertyChanged("l1");
				this.Onl1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> loginDateTime
	{
		get
		{
			return this._loginDateTime;
		}
		set
		{
			if ((this._loginDateTime != value))
			{
				this.OnloginDateTimeChanging(value);
				this.SendPropertyChanging();
				this._loginDateTime = value;
				this.SendPropertyChanged("loginDateTime");
				this.OnloginDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginIP", DbType="VarChar(20)")]
	public string loginIP
	{
		get
		{
			return this._loginIP;
		}
		set
		{
			if ((this._loginIP != value))
			{
				this.OnloginIPChanging(value);
				this.SendPropertyChanging();
				this._loginIP = value;
				this.SendPropertyChanged("loginIP");
				this.OnloginIPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentId", DbType="Int NOT NULL")]
	public int parentId
	{
		get
		{
			return this._parentId;
		}
		set
		{
			if ((this._parentId != value))
			{
				this.OnparentIdChanging(value);
				this.SendPropertyChanging();
				this._parentId = value;
				this.SendPropertyChanged("parentId");
				this.OnparentIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> createDateTime
	{
		get
		{
			return this._createDateTime;
		}
		set
		{
			if ((this._createDateTime != value))
			{
				this.OncreateDateTimeChanging(value);
				this.SendPropertyChanging();
				this._createDateTime = value;
				this.SendPropertyChanged("createDateTime");
				this.OncreateDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> updateDateTime
	{
		get
		{
			return this._updateDateTime;
		}
		set
		{
			if ((this._updateDateTime != value))
			{
				this.OnupdateDateTimeChanging(value);
				this.SendPropertyChanging();
				this._updateDateTime = value;
				this.SendPropertyChanged("updateDateTime");
				this.OnupdateDateTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateUserId", DbType="Int")]
	public System.Nullable<int> updateUserId
	{
		get
		{
			return this._updateUserId;
		}
		set
		{
			if ((this._updateUserId != value))
			{
				this.OnupdateUserIdChanging(value);
				this.SendPropertyChanging();
				this._updateUserId = value;
				this.SendPropertyChanged("updateUserId");
				this.OnupdateUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_walletAmount", DbType="Decimal(18,4) NOT NULL")]
	public decimal walletAmount
	{
		get
		{
			return this._walletAmount;
		}
		set
		{
			if ((this._walletAmount != value))
			{
				this.OnwalletAmountChanging(value);
				this.SendPropertyChanging();
				this._walletAmount = value;
				this.SendPropertyChanged("walletAmount");
				this.OnwalletAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="Decimal(18,4)")]
	public System.Nullable<decimal> rate
	{
		get
		{
			return this._rate;
		}
		set
		{
			if ((this._rate != value))
			{
				this.OnrateChanging(value);
				this.SendPropertyChanging();
				this._rate = value;
				this.SendPropertyChanged("rate");
				this.OnrateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_betSetting", DbType="VarChar(MAX)")]
	public string betSetting
	{
		get
		{
			return this._betSetting;
		}
		set
		{
			if ((this._betSetting != value))
			{
				this.OnbetSettingChanging(value);
				this.SendPropertyChanging();
				this._betSetting = value;
				this.SendPropertyChanged("betSetting");
				this.OnbetSettingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginGuid", DbType="VarChar(100)")]
	public string loginGuid
	{
		get
		{
			return this._loginGuid;
		}
		set
		{
			if ((this._loginGuid != value))
			{
				this.OnloginGuidChanging(value);
				this.SendPropertyChanging();
				this._loginGuid = value;
				this.SendPropertyChanged("loginGuid");
				this.OnloginGuidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="NVarChar(50)")]
	public string nickname
	{
		get
		{
			return this._nickname;
		}
		set
		{
			if ((this._nickname != value))
			{
				this.OnnicknameChanging(value);
				this.SendPropertyChanging();
				this._nickname = value;
				this.SendPropertyChanged("nickname");
				this.OnnicknameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
